name: Dependency Review

on:
  pull_request:
    branches: [main, develop, optimize]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the workflow if vulnerabilities are found
          fail-on-severity: moderate
          # Allow specific packages if needed
          # allow-licenses: MIT, Apache-2.0
          # deny-licenses: GPL-2.0, GPL-3.0
